[packages]
apt = [
  "libnss3","libatk1.0-0","libatk-bridge2.0-0","libcups2","libgbm1",
  "libasound2t64","libpangocairo-1.0-0","libxss1","libgtk-3-0",
  "libxshmfence1","libglu1","libgdk-pixbuf2.0-0","libgobject-2.0-0",
  "libdrm2","libx11-6","libxcomposite1","libxdamage1","libxext6",
  "libxfixes3","libxrandr2","libxcb1","libxkbcommon0","libpango-1.0-0",
  "libcairo2","libicu72","libffi8","libx264-164","chromium"
]
