[phases.setup]
nixPkgs = ["python311"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[phases.start]
cmd = "./start.sh"

[packages]
apt = [
  "libnss3", "libatk1.0-0", "libatk-bridge2.0-0", "libcups2", "libgbm1",
  "libasound2", "libpangocairo-1.0-0", "libxss1", "libgtk-3-0",
  "libxshmfence1", "libglu1", "chromium"
]
